;(function(){function r(val,args){for(var x=0;x<args.length;x++){val=val.replace('{'+x+'}',args[x]);}
return val;}
function p(){var val=arguments[0];var ret;if(val.indexOf('{0}')!=-1)
ret=function(){return r(val,arguments);}
else ret=function(){return val;}
for(var x=1;x<arguments.length;x++){for(var a in arguments[x])
ret[a]=arguments[x][a];}
return ret;}
window.detail=({"RECORD_REF_PRINT_SELECTED":p("Print the selected references"),"RECORD_PUBLICATION_ALT":p("View the {0} publications that cite this one"),"RECORD_REF_BIB_SELECTED":p("Create a bibliography for the selected references"),"RECORD_REF_PRINT_SELECTED_Disable":p("Please select one or more document(s) below to Print"),"RECORD_ALERT_ME":p("Alert me"),"RECORD_ALERT_CITED_IN_SCOPUS":p("when this document is cited in Scopus"),"RECORD_JS_MENDELEY_TOP_DEMOGRAPHICS":p("Top demographics"),"RECORD_PAGE_ADD_LIST":p("Add to My List"),"RECORD_JS_MENDELEY_PERSON":p("{0} person has saved this article to Mendeley"),"RECORD_PAGE_PRINT":p("Print"),"RECORD_JS_MENDELEY_ERROR":p("We are unable to load this content at this time.<br/><br/>Please check back later."),"RECORD_PAGE_CREATE_BIB":p("Create bibliography"),"RECORD_PAGE_RET":p("Retrieving..."),"RECORD_REF_EMAIL_SELECTED":p("Email the selected references"),"RECORD_JS_MENDELEY_PEOPLE":p("{0} people have saved this article to Mendeley"),"RECORD_JS_MENDELEY_TOP_DISCIPLINES":p("Top disciplines"),"RECORD_LOADING_RETRIEVING_COUNTS":p("Retrieving citations..."),"RECORD_REF_BIB_SELECTED_Disable":p("Please select one or more document(s) below to Create a bibliography"),"RECORD_JS_MENDELEY_TOP_COUNTRIES":p("Top countries"),"RECORD_PUBLICATION":p("Cited {0} times"),"RECORD_PAGE_RET_AFFIL":p("Retrieving additional affiliations..."),"RECORD_PAGE_DOWNLOAD":p("Download"),"RECORD_REF_EMAIL_SELECTED_Disable":p("Please select one or more document(s) below to E-mail"),"RECORD_PAGE_RET_AUTHOR":p("Retrieving additional authors..."),"RECORD_PAGE_VIEW_AUTHOR":p("View additional authors"),"RECORD_PAGE_HIDE_AFFIL":p("Hide additional affiliations"),"RECORD_PAGE_EMAIL":p("E-mail"),"RECORD_PAGE_HIDE_AUTHOR":p("Hide additional authors"),"RECORD_PAGE_VIEW_AFFIL":p("View additional affiliations")})})();;(function(){function r(val,args){for(var x=0;x<args.length;x++){val=val.replace('{'+x+'}',args[x]);}
return val;}
function p(){var val=arguments[0];var ret;if(val.indexOf('{0}')!=-1)
ret=function(){return r(val,arguments);}
else ret=function(){return val;}
for(var x=1;x<arguments.length;x++){for(var a in arguments[x])
ret[a]=arguments[x][a];}
return ret;}
window.gadget=({"GADGET_ABT_APP":p("About This App"),"GADGET_MANAGE_APPLICATIONS":p("Manage Applications"),"GADGET_TURN_ON":p("Turn On"),"GADGET_ADD_APPLICATIONS":p("Add Applications"),"GADGET_EDIT_PREFS":p("Edit Preferences"),"GADGET_REMOVE_PRMOPT":p("Are you sure that you want to permanently delete this application?"),"GADGET_MOVE_UP":p("Move UP"),"GADGET_REMOVE":p("Remove"),"GADGET_CLOSE_APP":p("Close This Application"),"GADGET_MANAGE_APPS":p("Manage Apps"),"GADGET_CLOSE":p("Close"),"GADGET_TURN_OFF":p("Turn Off"),"GADGET_PIN":p("Pin"),"GADGET_NO_APPS":p("You currently have no applications"),"GADGET_HIDE_PROMPT":p("This application is provided to you by your institution or is available to all users. You cannot remove it but can only hide it. If you hide it it will only be available on your My Aplications page and you can un-hide it there. Would you like to Hide this application?"),"GADGET_OPEN_APP":p("Open This Application"),"GADGET_OPEN_OPTIONS":p("Open Options"),"GADGET_SHOW_FEWER":p("Show fewer applications"),"GADGET_OPEN_CANVAS":p("Open Application To Full-Screen Mode"),"GADGET_MOVE_DOWN":p("Move DOWN"),"GADGET_MOVE_APP":p("Move Application"),"GADGET_ADD_APPS":p("Add Apps"),"GADGET_UNPIN":p("Unpin"),"GADGET_HELP":p("Help"),"GADGET_SHOW_MORE":p("Show more applications")})})();function writeXmlHttpRequestCookie()
{document.cookie="xmlHttpRequest=true; path=/";}
jQuery(writeXmlHttpRequestCookie);function internalServerErrorHandler(request){if(request.getResponseHeader("sessionExpired")=="true")
{window.location="../standard/sessionexpired.url";}}
var g_MAX_DOWNLOAD_DOC_COUNT;function PDFdownloadFromResultsPage(control){checkMaxDownloadDocsExceeded(control);var returnVal=true;if(g_maxDownloadSelectedExceeded){g_maxDownloadSelectedExceeded=false;returnVal=confirm(messages.results.error.max.download.exc(g_MAX_DOWNLOAD_DOC_COUNT));}
selCount=getSelectedDocumentCount(control);if(!g_maxDownloadSelectedExceeded&&selCount>0&&returnVal){openDownloadWindow('');document.SearchResultsForm.clickedLink.value="downloadButton";document.SearchResultsForm.target="downloadMain";document.SearchResultsForm.submit();}
return false;}
function PDFdownloadFromRecordPage(control,url){openDownloadWindow(url);return true;}
function openDownloadWindow(url){if((navigator.appName=="Microsoft Internet Explorer")&&(parseFloat(navigator.appVersion)<4))
{return false;}
var parms='width=800'+',height=560'+',screenX=0'+',screenY=0'+',left=0'+',top=0'+',status=yes,toolbar=no,menubar=no,location=no'+',scrollbars=yes,resizable=yes';win=window.open(url,'downloadMain',parms);win.focus();return false;}
function openSeperateWindow(pageToLoad,winName,width,height,center)
{if(winName=='popuptip'){loc=2;}else{loc=0;}
args=getArgs(width,height,center,0,loc);if((parseInt(navigator.appVersion)>=4)&&(center)){if(window.sepwindow){sepwindow.close();sepwindow=window.open(pageToLoad,winName,args);}}
sepwindow=window.open(pageToLoad,winName,args);return false;}
function openGlobalhelp(pageToLoad,winName,width,height,center){if(winName=='popuptip'){loc=2;}else{loc=0;}
args=getArgs(width,height,center,0,loc);if((parseInt(navigator.appVersion)>=4)&&(center)){if(window.globalhelp){globalhelp.close();globalhelp=window.open(pageToLoad,winName,args);}}
globalhelp=window.open(pageToLoad,winName,args);return false;}
function getArgs(width,height,center,menu,loc){xposition=10;yposition=10;if((parseInt(navigator.appVersion)>=4)&&(center)){if(loc==0){xposition=(screen.width-width)-10;yposition=(screen.height-height)-58;}else if(loc==1){xposition=(screen.width-width)/2;yposition=((screen.height-height)/2)-67;}else if(loc==2){xposition=(screen.width-width)-10;yposition=0;}}
if(navigator.appName=='Netscape'){width=width+25;height=height+25;}
args="width="+width+",height="+height+",toolbar="+menu+",menubar="+menu
+",screenx="+xposition+",screeny="+yposition+",left="+xposition+",top="+
yposition+",resizable=1,scrollbars=1,";return args;}
function openSizedWindow(url,winname){if((navigator.appName=="Microsoft Internet Explorer")&&(parseFloat(navigator.appVersion)<4))
{return false;}
var parms='width=750'+',height=450'+',screenX=0'+',screenY=0'+',left=0'+',top=0'+',status=yes,toolbar=yes,menubar=yes,location=yes'+',scrollbars=yes,resizable=yes';win=window.open(url,winname,parms);win.focus();return false;}
function openBareWindow(url,winname){if((navigator.appName=="Microsoft Internet Explorer")&&(parseFloat(navigator.appVersion)<4))
{return false;}
var parms='width=750'+',height=450'+',screenX=0'+',screenY=0'+',left=0'+',top=0'+',status=no,toolbar=no,menubar=no,location=no'+',scrollbars=no,resizable=no';win=window.open(url,winname,parms);win.focus();return false;}
function openPopUpWindow(url,title,width,height,pos,menubar,toolbar,status,resizable,scrollbars,location){var features=createWindowFeatures(width,height,pos,menubar,toolbar,status,resizable,scrollbars,location);return window.open(url,title,features);}
function createWindowFeatures(width,height,pos,menubar,toolbar,status,resizable,scrollbars,location){var xpos=0;var ypos=0;var xfudge=20;var yfudge=40;switch(pos){case 1:xpos=0;ypos=0;break;case 2:xpos=(screen.width-width-xfudge)/2;ypos=0;break;case 3:xpos=screen.width-width-xfudge;ypos=0;break;case 4:xpos=0;ypos=(screen.height-height-yfudge)/2;break;case 5:xpos=(screen.width-width-xfudge)/2;ypos=(screen.height-height-yfudge)/2;break;case 6:xpos=screen.width-width-xfudge;ypos=(screen.height-height-yfudge)/2;break;case 7:xpos=0;ypos=(screen.height-height-yfudge);break;case 8:xpos=(screen.width-width-xfudge)/2;ypos=(screen.height-height-yfudge);break;case 9:xpos=(screen.width-width-xfudge);ypos=(screen.height-height-yfudge-20);break;case 10:xpos=(screen.width-width-10);ypos=0;break;}
args="width="+width+",height="+height+",screenx="+xpos+",left="+xpos+",screeny="+ypos+",top="+ypos+",menubar="+menubar+",toolbar="+toolbar+",location="+location+",status="+status+",resizable="+resizable+",scrollbars="+scrollbars;return args;}
function getJSCheckedUrl(url){url=url+"&javascript=t";return url;}
function clearForm(form){for(var i=0;i<form.elements.length;i++){if(form.elements[i].type!="hidden"){if(form.elements[i].type=="checkbox"){form.elements[i].checked=false;}else{form.elements[i].value="";}}}
return false;}
function flipLogin(button,from){if(from=="loginbox"){var t=jQuery('#loginBox');var u=jQuery('#loginPlus');if(t.css('display')=="none"){t.css('display','block');u.removeClass('plus');u.addClass('minus bg2');}else{t.css('display','none');u.removeClass('minus bg2');u.addClass('plus');}
showLoginBoxPos();}
if(from=="logoutbox"){var t=jQuery('#logoutBox');var u=jQuery('#logoutPlus');if(t.css('display')=="none"){t.css('display','block');u.removeClass('plus');u.addClass('minus bg2');}else{t.css('display','none');u.removeClass('minus bg2');u.addClass('plus');}
showLogoutBoxPos();}}
function showLoginBoxPos(){var divJSLogin=jQuery('#divJSLogin');var divJSLoginWidth=jQuery('#divJSLogin').width();var loginBox=jQuery("#loginBox");var divJSLoginLeftPos=divJSLogin.offset().left;var totalWidthPos=divJSLoginLeftPos+divJSLoginWidth;var windowWidth=jQuery(window).width();loginBox.css('right',windowWidth-totalWidthPos);}
function showLogoutBoxPos(){var logoutPlus=jQuery('a#logoutPlus');var logoutPlusWidth=logoutPlus.width()+20;var logoutBox=jQuery("#logoutBox");var logoutPlusLeftPos=logoutPlus.offset().left;var totalWidthPos=logoutPlusLeftPos+logoutPlusWidth;var windowWidth=jQuery(window).width();logoutBox.css({'right':windowWidth-totalWidthPos,'top':'26px'});}
function submitForm(actionUri){var associationForm=document.getElementById("associationForm");associationForm.action=actionUri;jQuery("#associationForm input[name=http_method_name]").val("GET");associationForm.submit();}
jQuery.fn.selectRange=function(start,end){if(!end)end=start;return this.each(function(){if(this.setSelectionRange){this.focus();this.setSelectionRange(start,end);}else if(this.createTextRange){var range=this.createTextRange();range.collapse(true);range.moveEnd('character',end);range.moveStart('character',start);range.select();}});};function placeHolderInit(){var placeHolderSupport=false;var test=document.createElement('input');if('placeholder'in test)placeHolderSupport=true;if(!placeHolderSupport){jQuery('[placeholder]').unbind('keydown,blur,click').click(function(){jQuery(this).focus();jQuery(this).selectRange(0);}).keydown(function(){var input=jQuery(this);if(input.val()==input.attr('placeholder')){input.val('');input.removeClass('placeholder');}}).blur(function(){var input=jQuery(this);if(input.val()==''||input.val()==input.attr('placeholder')){input.addClass('placeholder');input.val(input.attr('placeholder'));}}).blur().parents('form').submit(function(){jQuery(this).find('[placeholder]').each(function(){var input=jQuery(this);if(input.val()==input.attr('placeholder')){input.val('');}});});}}
function processAlertClick(button){jQuery("#alertClick").val(button);document.SourceInfoFormBean.submit();}
jQuery(document).ready(function(){var txtZoneMsgBar=jQuery('#messageBar');if(txtZoneMsgBar.length){if(jQuery.trim(jQuery('#messageBar div').html())!=''){txtZoneMsgBar.addClass('displayBlock').removeClass('displayNone');}else{txtZoneMsgBar.addClass('displayNone').removeClass('displayBlock');}}
var pipeObj=jQuery("#hasjs");if(pipeObj!=null&&pipeObj!='undefined'&&pipeObj!=''){pipeObj.parent().css("background","none");}});var InfoBubble={bubbleTimeout:2,currentBubble:null,timeoutBubbleID:null,show:function(aID){var aBubble=document.getElementById(aID);if(aBubble&&aBubble!=this.currentBubble){this.hide();aBubble.style.display='inline';this.currentBubble=aBubble;}
if(this.timeoutBubbleID){clearTimeout(this.timeoutBubbleID);}},hide:function(){if(this.currentBubble){this.currentBubble.style.display='none';this.currentBubble=null;if(this.timeoutBubbleID){clearTimeout(this.timeoutBubbleID);}}},timeout:function(){this.timeoutBubbleID=setTimeout('InfoBubble.hide()',this.bubbleTimeout*1000);}}
function assertNotEmpty(control){assertNotEmpty(control,'');}
function assertNotEmpty(control,message){var reg=/\S/g;if(control.value==null||control.value==''||control.value.match(reg)==null){if(message!=null&&message!=''){alert(message);}
control.focus();control.select();return false;}
return true;}
function assertNotEmptyString(thisString){var reg=/\S/g;if(thisString==null||thisString==''||thisString.match(reg)==null){return false;}
return true;}<!--
function assertChecked(control,message){if(control==null){return false;}
var isChecked=false;if((typeof(control)=="object")||(typeof(control)=="function")){if(control[0]!=undefined){for(var i=0;i<control.length;++i){if(control[i].checked){isChecked=control[i].checked;break;}}}
else{isChecked=control.checked;}}
if(arguments.length>1){if(!isChecked){if((message!=null)&&(message!="")){alert(message);}}}
return isChecked;}
var sgf=sgf||{};sgf.labels={aboutApp:gadget.GADGET_ABT_APP(),addApplications:gadget.GADGET_ADD_APPLICATIONS(),addApps:gadget.GADGET_ADD_APPS(),close:gadget.GADGET_CLOSE(),closeApp:gadget.GADGET_CLOSE_APP(),editPrefs:gadget.GADGET_EDIT_PREFS(),help:gadget.GADGET_HELP(),hidePrompt:gadget.GADGET_HIDE_PROMPT(),manageApps:gadget.GADGET_MANAGE_APPS(),manageApplications:gadget.GADGET_MANAGE_APPLICATIONS(),moveApp:gadget.GADGET_MOVE_APP(),moveDown:gadget.GADGET_MOVE_DOWN(),moveUp:gadget.GADGET_MOVE_UP(),noApps:gadget.GADGET_NO_APPS(),openApp:gadget.GADGET_OPEN_APP(),openCanvas:gadget.GADGET_OPEN_CANVAS(),openOptions:gadget.GADGET_OPEN_OPTIONS(),pin:gadget.GADGET_PIN(),remove:gadget.GADGET_REMOVE(),removePrompt:gadget.GADGET_REMOVE_PRMOPT(),showFew:gadget.GADGET_SHOW_FEWER(),showMore:gadget.GADGET_SHOW_MORE(),turnOff:gadget.GADGET_TURN_OFF(),turnOn:gadget.GADGET_TURN_ON(),unpin:gadget.GADGET_UNPIN()};var g_formSubmitOK=true;var allowed=true;var reqFromhubLink=false;var hubPopupParams="directories=0,titlebar=0,toolbar=0,location=0,status=0,menubar=0,scrollbars=no,resizable=no";var chapterListEnabled;function toggleRefChkBoxes(control){for(var i=0;i<control.form.elements.length;++i){var eleControl=control.form.elements[i];if(eleControl.type=="checkbox"&&eleControl.name=="selectedEIDs"){eleControl.checked=control.checked;}}}
function toggleSelectAllChkBox(control){if(control.checked==false){control.form.selectAllCheckBox.checked=false;}
else{var allChecked=true;for(var i=0;i<control.form.elements.length;++i){var eleControl=control.form.elements[i];if(eleControl.type=="checkbox"&&eleControl.name=="selectedEIDs"){if(eleControl.checked==false){allChecked=false;break;}}}
control.form.selectAllCheckBox.checked=allChecked;}}
function searchHistory(link){document.RecordPageForm.clickedLink.value=link;document.RecordPageForm.submit();}
function viewAllReferences(){if(allowed){allowed=false;setTimeout("enableAllowed()",waitTime);return true;}else{return false;}}
function enableAllowed(){allowed=true;}
function submitReferencesLinks(button){document.RecordPageForm.clickedLink.value=button;document.RecordPageForm.submit();}
function bindHubLinks(){jQuery('#webLinkForHub').bind("click",function(){onClickHubLinks('w',webCategoryIdForHub);});jQuery('#patLinkForHub').bind("click",function(){onClickHubLinks('p',patCategoryIdForHub);});jQuery('#selSrcLinkForHub').bind("click",function(){onClickHubLinks('c',selSrcCategoryIdForHub);});}
function onClickHubLinks(extSearchTypeForHub,categoryId){var refJson=["{","refbibkeys:","\""+refbibkeysForHub+"\"",",","author:","\""+authorsForHub+"\"",",","title:","\""+titleForHub+"\"",",","year:","\""+yearForHub+"\"",",","sourceTitle:","\""+sourceTitleForHub+"\"",",","volume:","\""+volumeForHub+"\"",",","issue:","\""+issueForHub+"\"",",","pages:","\""+pagesForHub+"\"","}"];jQuery('#citedByJson').val(encodeURIComponent(refJson.join('')));jQuery('#extSearchType').val(extSearchTypeForHub);if((extSearchTypeForHub=='c')&&(selSrcValuesForHub.length>0)){jQuery('#selectedSources').val(selSrcValuesForHub);}
var redirectUrl='/redirect/linking.url?postSub=true&targetURL='+hubSearchUrl
+'&origin='+originForHub
+'&locationID='+locationIdForHub
+'&categoryID='+categoryId
+'&zone='+zoneForHub
+'&linkType='+linkTypeForHub;var targWin='hubDataInNewWindow_'+categoryId;window["hubWin_"+categoryId]=window.open('',targWin,hubPopupParams);jQuery.ajax({url:redirectUrl,type:"GET",success:function(){if(!isFromRecPageForHub){var reqDivId=jQuery('.resultsOptionalLinks').closest('form');var origAction=jQuery(reqDivId).attr('action');var origTarget=jQuery(reqDivId).attr('target');var origMethod=jQuery(reqDivId).attr('method');reqFromhubLink=true;jQuery(reqDivId).attr('action',hubSearchUrl);jQuery(reqDivId).attr('target',targWin);jQuery(reqDivId).attr('method','POST');jQuery(reqDivId).submit();jQuery(reqDivId).attr('action',origAction);jQuery(reqDivId).attr('target',origTarget);jQuery(reqDivId).attr('method',origMethod);}else{jQuery('#hubForm').attr('target',targWin);jQuery('#hubForm').submit();}
window["hubWin_"+categoryId].focus();},error:function(){window["hubWin_"+categoryId].close();}});}
var authorlistHeight=jQuery('p#authorlist').height();var affiliationlistHeight=jQuery('p#affiliationlist').height();var authorlistParagraph=jQuery('p#authorlist');var affilListParagraph=jQuery('p#affiliationlist');if(jQuery('p#affiliationlist span').length>3){var affilListCountHeight=jQuery('p#affiliationlist span').eq(0).outerHeight()+jQuery('p#affiliationlist span').eq(1).outerHeight()+jQuery('p#affiliationlist span').eq(2).outerHeight();var defaultAffilHeight;if(jQuery.browser.msie){defaultAffilHeight=affilListCountHeight+37;}
else if(jQuery.browser.webkit){defaultAffilHeight=affilListCountHeight+28;}
else{defaultAffilHeight=affilListCountHeight+18;}}
var defaultListHeight=62;function displayAuthAffilInRecordPage(){var cnt=0;jQuery('div.reaxysBlk').css({display:'block',position:'absolute',visible:'hidden'});jQuery('div.reaxysBlk a img').each(function(){if(jQuery(this)[0].clientHeight<=1){cnt++;}});jQuery('div.reaxysBlk').css({display:'none',position:'',visible:'visible'});if(cnt<=0){jQuery('div.reaxysBlk').show();jQuery('div.reaxysHide').show();}
if(cnt==1){jQuery('div.reaxysBlk span.divider').hide();jQuery('div.reaxysBlk').show();jQuery('div.reaxysHide').show();}
var totalSpan=jQuery('#authorlist > span').size();var temp='',prevTemp='';var endSpan;var containerSpan=jQuery('<div>').appendTo('#SpanContainer');endSpan="(...), <span>"
+jQuery('#authorlist > span').eq(totalSpan-2).html()+"</span><span>"
+jQuery('#authorlist > span').eq(totalSpan-1).html()+"</span>";for(var j=0;j<totalSpan;j++){for(var i=0;i<=j;i++){temp+="<span>"+jQuery('#authorlist > span').eq(i).html()+"</span>";}
jQuery(containerSpan).html(temp+endSpan);if(jQuery(containerSpan).height()>80){temp="";jQuery(containerSpan).html(prevTemp+endSpan);j=totalSpan;}else{prevTemp=temp;temp="";jQuery(containerSpan).html("");}}
if(authorlistHeight>defaultListHeight){jQuery('#authorlist').hide();jQuery('#SpanContainer').show();jQuery('#viewHideAuthorList').css({'display':'inline-block'});jQuery('#viewHideAuthorList-dummy').css({'display':'inline-block'});}else{jQuery('#SpanContainer').hide();jQuery(authorlistParagraph).css({'height':'auto','overflow':'visible','display':'block'});jQuery('#viewHideAuthorList').css({'display':'none'});jQuery('#viewHideAuthorList-dummy').css({'display':'none'});}
if(affiliationlistHeight>defaultAffilHeight){jQuery(affilListParagraph).css({'height':defaultAffilHeight+'px','overflow':'hidden','visibility':'visible'});jQuery('#viewHideAffilList').css({'display':'inline-block'});jQuery('#viewHideAffilList-dummy').css({'display':'inline-block'});}else{jQuery(affilListParagraph).css({'height':'auto','overflow':'visible','visibility':'visible'});jQuery('#viewHideAffilList').css({'display':'none'});jQuery('#viewHideAffilList-dummy').css({'display':'none'});}}
function showAffilContent(){jQuery('#viewHideAffilList a').html(detail.RECORD_PAGE_HIDE_AFFIL());jQuery(affilListParagraph).css({'height':'auto','overflow':'visible'});jQuery('#viewHideAffilList a').addClass('hideAddIcon').removeClass('viewAddIcon retrievingImg');jQuery('#viewHideAffilList a').attr('title',detail.RECORD_PAGE_HIDE_AFFIL());jQuery('#viewHideAffilList a').unbind('click').bind('click',function(){showHideAffilContent();});}
var AffilContentLoaded=false;function showHideAffilContent(){if(jQuery('#viewHideAffilList a').html()==detail.RECORD_PAGE_VIEW_AFFIL()){if(!AffilContentLoaded){jQuery("#viewHideAffilList a").html(detail.RECORD_PAGE_RET()).addClass('retrievingImg').removeClass('viewAddIcon').unbind('click');jQuery('#AffRetriving').css({'display':'inline-block'}).delay(5000).hide('0',function(){showAffilContent();AffilContentLoaded=true;});}else{showAffilContent();}}
else{jQuery('#viewHideAffilList a').html(detail.RECORD_PAGE_VIEW_AFFIL());jQuery(affilListParagraph).css({'height':defaultAffilHeight+'px','overflow':'hidden'});jQuery('#viewHideAffilList a').addClass('viewAddIcon').removeClass('hideAddIcon');jQuery('#viewHideAffilList a').attr('title',detail.RECORD_PAGE_VIEW_AFFIL());}}
jQuery('#viewHideAffilList a').unbind('click').bind('click',function(){showHideAffilContent();});function showAuthorContent(){jQuery('#viewHideAuthorList a').html(detail.RECORD_PAGE_HIDE_AUTHOR());jQuery(authorlistParagraph).css({'height':'auto','overflow':'visible'});jQuery('#viewHideAuthorList a').addClass('hideAddIcon').removeClass('viewAddIcon retrievingImg');jQuery('#viewHideAuthorList a').attr('title',detail.RECORD_PAGE_HIDE_AUTHOR());jQuery('#viewHideAuthorList a').unbind('click').bind('click',function(){showHideAuthorContent();});jQuery('#authorlist').show();jQuery('#SpanContainer').hide();}
var AuthorContentLoaded=false;function showHideAuthorContent(){if(jQuery('#viewHideAuthorList a').html()==detail.RECORD_PAGE_VIEW_AUTHOR()){if(!AuthorContentLoaded){jQuery("#viewHideAuthorList a").html(detail.RECORD_PAGE_RET()).addClass('retrievingImg').removeClass('viewAddIcon').unbind('click');jQuery('#AuthorRetriving').css({'display':'inline-block'}).delay(5000).hide('0',function(){showAuthorContent();AuthorContentLoaded=true;jQuery('#authorlist').show();jQuery('#SpanContainer').hide();});}else{showAuthorContent();}}
else{jQuery('#viewHideAuthorList a').html(detail.RECORD_PAGE_VIEW_AUTHOR());jQuery(authorlistParagraph).css({'height':defaultListHeight+'px','overflow':'hidden'});jQuery('#viewHideAuthorList a').addClass('viewAddIcon').removeClass('hideAddIcon');jQuery('#viewHideAuthorList a').attr('title',detail.RECORD_PAGE_VIEW_AUTHOR());jQuery('#authorlist').hide();jQuery('#SpanContainer').show();}}
jQuery('#viewHideAuthorList a').unbind('click').bind('click',function(){showHideAuthorContent();});jQuery('body').bind('click',function(e){if(!jQuery(e.target).closest('.recMoreLnk')){jQuery('.recMoreMenu').hide();}});jQuery('.arrowDownMore').click(function(e){var recmoreLnk=jQuery('.recMoreLnk');var recmoreLnkPosition=recmoreLnk.position();jQuery('.recMoreMenu').hide();if(recmoreLnkPosition!=null)
jQuery('#recMoreMenu').css({'display':'block','top':recmoreLnkPosition.top+4});});jQuery('.arrowUpMore').click(function(e){jQuery('.recMoreMenu').hide();});function getChapterList(){var chapterListUrl='/display/chapter.url';var sourceId=jQuery('#sourceId').val();var sourceType=jQuery('#sourceType').val();var citationType=jQuery('#citationType').val();var currentEID=jQuery("#currentRecordPageEID").val();if(sourceId!=null&&sourceId!=''&&sourceType!=null&&sourceType!='')
{if(sourceType=='b'){param={sourceId:sourceId,requestedPage:"bookChapter",currentRecordPageEID:currentEID,citationCode:citationType};jQuery.ajax({url:chapterListUrl,dataType:"html",cache:false,data:param,type:"POST",success:function(data){if(data!=null&&data!=''){jQuery("#chapterList").html(data);jQuery('#chapterList').show();var bookEID=jQuery('#bookEID').val();if(jQuery('#sourceTitleId').length&&bookEID!=null&&bookEID!=''&&citationType!='bk'){jQuery('#sourceTitleId').attr('href','/record/display.url?eid='+bookEID+'&origin=recordpage');jQuery('#sourceTitleId').removeClass('bookChapterLink');}}},error:function(data){}});}}}
function enableReferenceHeaderLnk(){if(jQuery("div.referenceLists input:checkbox:checked").length>0){jQuery('div.featuresRow span.docHeaderLinks').removeClass('lnkDisabled').addClass('lnkEnabled');showRefernceEnableToolTip();}
else{jQuery('div.featuresRow span.docHeaderLinks').addClass('lnkDisabled').removeClass('lnkEnabled');showRefernceDisableToolTip();}}
function enableDiableReferencesHeaderLnk(){if(jQuery("div.referenceLists input:checkbox:checked").length>0){enableReferenceHeaderLnk();}else{var directExport=jQuery('#referenceDirectExport');if(directExport.length>0){directExport.attr('title',Export.EXPORT_DISABLED_ALT());}}
jQuery('div.referenceLists input:checkbox, div.featuresRow input:checkbox').click(function(){enableReferenceHeaderLnk();});jQuery('body').on('click','.lnkDisabled a.clickAction',function(e){e.preventDefault();});jQuery('body').on('click','.lnkEnabled a.clickAction',function(e){var linkType=jQuery(this).attr('data-type');if(linkType=='exportLink'||linkType=='exportRecordLink'){oneClick.exportResult(e);}else if(linkType=='printLink'){submitReferencesLinks('Print');}else if(linkType=='emailLink'){submitReferencesLinks('Email');}
else if(linkType=='bibliographyLink'){submitReferencesLinks('Quikbib');}else if(linkType=='directExport'){oneClick.oneClickExportSubmit(e,false,'record');}else if(linkType=='directExportReference'){oneClick.oneClickExportSubmit(e,false,'reference');}});}
function showRefernceEnableToolTip(){var exportLink=Export.EXPORT_RECORD_REF_EXP_SELECTED();var printLink=detail.RECORD_REF_PRINT_SELECTED();var emailLink=detail.RECORD_REF_EMAIL_SELECTED();var biblioLink=detail.RECORD_REF_BIB_SELECTED();jQuery('.docHeaderLinks .print').attr('title',printLink);jQuery('.docHeaderLinks .email').attr('title',emailLink);jQuery('.docHeaderLinks .createBibliography').attr('title',biblioLink);var directExportRefObj=jQuery('#referenceDirectExport');if(directExportRefObj.length>0){var directExportTitle;if(oneClick.ExportSetting.Format=='CSV'){directExportTitle=Export.CSV_EXPORT_ALT();}
else if(oneClick.ExportSetting.Format=='REFWORKS'){directExportTitle=Export.REFWORK_EXPORT_ALT();}
else if(oneClick.ExportSetting.Format=='Mendeley'){directExportTitle=Export.SAVE_TO_MENDELEY_ALT();}
else if(oneClick.ExportSetting.Format=='RIS'){directExportTitle=Export.RIS_EXPORT_ALT();}
else if(oneClick.ExportSetting.Format=='TEXT'){directExportTitle=Export.TEXT_EXPORT_ALT();}
else if(oneClick.ExportSetting.Format=='BIB'){directExportTitle=Export.BIBTEXT_EXPORT_ALT();}
directExportRefObj.attr('title',directExportTitle);}else{jQuery('.docHeaderLinks .exportRefNormal').attr('title',exportLink);}}
function showRefernceDisableToolTip(){var disabledExport=Export.EXPORT_DISABLED_ALT();var disabledPrint=detail.RECORD_REF_PRINT_SELECTED_Disable();var disabledEmail=detail.RECORD_REF_EMAIL_SELECTED_Disable();var disabledBiblio=detail.RECORD_REF_BIB_SELECTED_Disable();jQuery('.docHeaderLinks .print').attr('title',disabledPrint);jQuery('.docHeaderLinks .email').attr('title',disabledEmail);jQuery('.docHeaderLinks .createBibliography').attr('title',disabledBiblio);var directExportRefObj=jQuery('.docHeaderLinks .directExport');if(directExportRefObj.length>0){directExportRefObj.attr('title',disabledExport);}else{jQuery('.docHeaderLinks .exportRefNormal').attr('title',disabledExport);}}
function showRemoteAccPopUp(message,timeOut)
{document.getElementById("popUpDisplay").style.display="block";setCenterAlign();setTimeout(hideRemoteAccessModalBox,timeOut);}
function hideRemoteAccessModalBox()
{document.getElementById("popUpDisplay").style.display="none";}
function setCenterAlign()
{var msgBox=document.getElementById('modalWindowMsgBox');var winWidth=getWindowWidth();var winHeight=getWindowHeight();var top=(winHeight-msgBox.offsetHeight)/2;var left=(winWidth-msgBox.offsetWidth)/2;msgBox.style.top=top+'px';msgBox.style.left=left+'px';document.getElementById('modalWindow').style.height=winHeight+'px';};function getWindowHeight()
{var myHeight=0;if(typeof(window.innerWidth)=='number'){myHeight=window.innerHeight;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){myHeight=document.documentElement.clientHeight;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){myHeight=document.body.clientHeight;}
return myHeight;};function getWindowWidth()
{var myWidth=0;if(typeof(window.innerWidth)=='number'){myWidth=window.innerWidth;}else if(document.documentElement&&(document.documentElement.clientWidth||document.documentElement.clientHeight)){myWidth=document.documentElement.clientWidth;}else if(document.body&&(document.body.clientWidth||document.body.clientHeight)){myWidth=document.body.clientWidth;}
return myWidth;};;(function(selectBoxIt){"use strict";selectBoxIt(window.jQuery,window,document);}
(function($,window,document,undefined){"use strict";$.widget("selectBox.selectBoxIt",{VERSION:"3.7.0",options:{"showEffect":"none","showEffectOptions":{},"showEffectSpeed":"medium","hideEffect":"none","hideEffectOptions":{},"hideEffectSpeed":"medium","showFirstOption":true,"defaultText":"","defaultIcon":"","downArrowIcon":"","theme":"default","keydownOpen":true,"isMobile":function(){var ua=navigator.userAgent||navigator.vendor||window.opera;return(/iPhone|iPod|iPad|Silk|Android|BlackBerry|Opera Mini|IEMobile/).test(ua);},"native":false,"aggressiveChange":false,"selectWhenHidden":true,"viewport":$(window),"similarSearch":false,"copyAttributes":["title","rel"],"copyClasses":"button","nativeMousedown":false,"customShowHideEvent":false,"autoWidth":false,"html":true,"populate":"","dynamicPositioning":true,"hideCurrent":false},"getThemes":function(){var self=this,theme=$(self.element).attr("data-theme")||"c";return{"bootstrap":{"focus":"active","hover":"","enabled":"enabled","disabled":"disabled","arrow":"caret","button":"btn","list":"dropdown-menu","container":"bootstrap","open":"open"},"jqueryui":{"focus":"ui-state-focus","hover":"ui-state-hover","enabled":"ui-state-enabled","disabled":"ui-state-disabled","arrow":"ui-icon ui-icon-triangle-1-s","button":"ui-widget ui-state-default","list":"ui-widget ui-widget-content","container":"jqueryui","open":"selectboxit-open"},"jquerymobile":{"focus":"ui-btn-down-"+theme,"hover":"ui-btn-hover-"+theme,"enabled":"ui-enabled","disabled":"ui-disabled","arrow":"ui-icon ui-icon-arrow-d ui-icon-shadow","button":"ui-btn ui-btn-icon-right ui-btn-corner-all ui-shadow ui-btn-up-"+theme,"list":"ui-btn ui-btn-icon-right ui-btn-corner-all ui-shadow ui-btn-up-"+theme,"container":"jquerymobile","open":"selectboxit-open"},"default":{"focus":"selectboxit-focus","hover":"selectboxit-hover","enabled":"selectboxit-enabled","disabled":"selectboxit-disabled","arrow":"selectboxit-default-arrow","button":"selectboxit-btn","list":"selectboxit-list","container":"selectboxit-container","open":"selectboxit-open"}};},isDeferred:function(def){return $.isPlainObject(def)&&def.promise&&def.done;},_create:function(internal){var self=this,populateOption=self.options["populate"];if(!self.element.is("select")){return;}
self.widgetProto=$.Widget.prototype;self.originalElem=self.element[0];self.selectBox=self.element;if(self.options["populate"]&&self.add&&!internal){self.add(populateOption);}
self.selectItems=self.element.find("option");self.firstSelectItem=self.selectItems.slice(0,1);self.documentHeight=$(document).height();self.theme=self.getThemes()[self.options["theme"]]||self.getThemes()["default"];self.currentFocus=0;self.blur=true;self.textArray=[];self.currentIndex=0;self.currentText="";self.flipped=false;if(!internal){self.selectBoxStyles=self.selectBox.attr("style");}
self._createDropdownButton()._createUnorderedList()._copyAttributes()._replaceSelectBox()._addClasses(self.theme)._eventHandlers();if(self.originalElem.disabled&&self.disable){self.disable();}
if(self._ariaAccessibility){self._ariaAccessibility();}
self.isMobile=self.options["isMobile"]();if(self._mobile){self._mobile();}
if(self.options["native"]){this._applyNativeSelect();}
self.triggerEvent("create");return self;},_createDropdownButton:function(){var self=this,originalElemId=self.originalElemId=self.originalElem.id||"",originalElemValue=self.originalElemValue=self.originalElem.value||"",originalElemName=self.originalElemName=self.originalElem.name||"",copyClasses=self.options["copyClasses"],selectboxClasses=self.selectBox.attr("class")||"";self.dropdownText=$("<span/>",{"id":originalElemId&&originalElemId+"SelectBoxItText","class":"selectboxit-text","unselectable":"on","text":self.firstSelectItem.text()}).attr("data-val",originalElemValue);self.dropdownImageContainer=$("<span/>",{"class":"selectboxit-option-icon-container"});self.dropdownImage=$("<i/>",{"id":originalElemId&&originalElemId+"SelectBoxItDefaultIcon","class":"selectboxit-default-icon","unselectable":"on"});self.dropdown=$("<span/>",{"id":originalElemId&&originalElemId+"SelectBoxIt","class":"selectboxit "+(copyClasses==="button"?selectboxClasses:"")+" "+(self.selectBox.prop("disabled")?self.theme["disabled"]:self.theme["enabled"]),"name":originalElemName,"tabindex":self.selectBox.attr("tabindex")||"0","unselectable":"on"}).append(self.dropdownImageContainer.append(self.dropdownImage)).append(self.dropdownText);self.dropdownContainer=$("<span/>",{"id":originalElemId&&originalElemId+"SelectBoxItContainer","class":"selectboxit-container "+(copyClasses==="container"?selectboxClasses:"")}).append(self.dropdown);return self;},_createUnorderedList:function(){var self=this,dataDisabled,optgroupClass,optgroupElement,iconClass,iconUrl,iconUrlClass,iconUrlStyle,currentItem="",originalElemId=self.originalElemId||"",createdList=$("<ul/>",{"id":originalElemId&&originalElemId+"SelectBoxItOptions","class":"selectboxit-options","tabindex":-1}),currentDataSelectedText,currentDataText,currentText,parent;if(!self.options["showFirstOption"]){self.selectItems.first().attr("disabled","disabled");self.selectItems=self.selectBox.find("option").slice(1);}
self.selectItems.each(function(index){optgroupClass="";optgroupElement="";dataDisabled=$(this).prop("disabled");iconClass=$(this).attr("data-icon")||"";iconUrl=$(this).attr("data-iconurl")||"";iconUrlClass=iconUrl?"selectboxit-option-icon-url":"";iconUrlStyle=iconUrl?'style="background-image:url(\''+iconUrl+'\');"':"";currentDataSelectedText=$(this).attr("data-selectedtext");currentDataText=$(this).attr("data-text");currentText=currentDataText?currentDataText:$(this).html();parent=$(this).parent();if(parent.is("optgroup")){optgroupClass="selectboxit-optgroup-option";if($(this).index()===0){optgroupElement='<span class="selectboxit-optgroup-header '+parent.first().attr("class")+'"data-disabled="true">'+parent.first().attr("label")+'</span>';}}
currentItem+=optgroupElement+'<li id="'+index+'" data-val="'+this.value+'" data-disabled="'+dataDisabled+'" class="'+optgroupClass+" selectboxit-option "+($(this).attr("class")||"")+'"><a class="selectboxit-option-anchor"><span class="selectboxit-option-icon-container"><i class="selectboxit-option-icon '+iconClass+' '+(iconUrlClass||self.theme["container"])+'"'+iconUrlStyle+'></i></span>'+(self.options["html"]?currentText:self.htmlEscape(currentText))+'</a></li>';self.textArray[index]=dataDisabled?"":currentText;if(this.selected){self._setText(self.dropdownText,currentDataSelectedText||currentText);self.currentFocus=index;}});if((self.options["defaultText"]||self.selectBox.attr("data-text"))){var defaultedText=self.options["defaultText"]||self.selectBox.attr("data-text");self._setText(self.dropdownText,defaultedText);self.options["defaultText"]=defaultedText;}
createdList.append(currentItem);self.list=createdList;self.dropdownContainer.append(self.list);self.listItems=self.list.children("li");self.listAnchors=self.list.find("a");self.listItems.first().addClass("selectboxit-option-first");self.listItems.last().addClass("selectboxit-option-last");self.list.find("li[data-disabled='true']").not(".optgroupHeader").addClass(self.theme["disabled"]);self.dropdownImage.addClass(self.selectBox.attr("data-icon")||self.options["defaultIcon"]||self.listItems.eq(self.currentFocus).find("i").attr("class"));self.dropdownImage.attr("style",self.listItems.eq(self.currentFocus).find("i").attr("style"));return self;},_replaceSelectBox:function(){var self=this,height,originalElemId=self.originalElem.id||"",size=self.selectBox.attr("data-size"),listSize=self.listSize=size===undefined?"auto":size==="0"||"size"==="auto"?"auto":+size;self.selectBox.css("display","none").after(self.dropdownContainer);height=self.dropdown.height();self.downArrow=$("<i/>",{"id":originalElemId&&originalElemId+"SelectBoxItArrow","class":"selectboxit-arrow","unselectable":"on"});self.downArrowContainer=$("<span/>",{"id":originalElemId&&originalElemId+"SelectBoxItArrowContainer","class":"selectboxit-arrow-container","unselectable":"on"}).append(self.downArrow);self.dropdown.append(self.downArrowContainer);self.listItems.removeClass("selectboxit-selected").eq(self.currentFocus).addClass("selectboxit-selected");if(!self._realOuterWidth(self.dropdownImageContainer)){self.dropdownImageContainer.remove();}
if(self.options["autoWidth"]){if(self.dropdown.is(":visible")){self.dropdown.css({"width":"auto"}).css({"width":self.list.outerWidth(true)+self.downArrowContainer.outerWidth(true)+self.dropdownImage.outerWidth(true)});}
else{self.dropdown.css({"width":"auto"}).css({"width":self._realOuterWidth(self.list)+self._realOuterWidth(self.downArrowContainer)+self._realOuterWidth(self.dropdownImage)});}
self.list.css({"min-width":self.dropdown.width()});}
self.dropdownContainer.addClass('selectboxit-rendering');self.dropdownText.css({"max-width":self.dropdownContainer.outerWidth(true)-(self.downArrowContainer.outerWidth(true)+self.dropdownImage.outerWidth(true))});self.dropdownContainer.removeClass('selectboxit-rendering');if($.type(listSize)==="number"){self.maxHeight=self.listAnchors.outerHeight(true)*listSize;}
return self;},_scrollToView:function(type){var self=this,currentOption=self.listItems.eq(self.currentFocus),listScrollTop=self.list.scrollTop(),currentItemHeight=currentOption.height(),currentTopPosition=currentOption.position().top,absCurrentTopPosition=Math.abs(currentTopPosition),listHeight=self.list.height(),currentText;if(type==="search"){if(listHeight-currentTopPosition<currentItemHeight){self.list.scrollTop(listScrollTop+(currentTopPosition-(listHeight-currentItemHeight)));}
else if(currentTopPosition<-1){self.list.scrollTop(currentTopPosition-currentItemHeight);}}
else if(type==="up"){if(currentTopPosition<-1){self.list.scrollTop(listScrollTop-absCurrentTopPosition);}}
else if(type==="down"){if(listHeight-currentTopPosition<currentItemHeight){self.list.scrollTop((listScrollTop+(absCurrentTopPosition-listHeight+currentItemHeight)));}}
return self;},_callbackSupport:function(callback){var self=this;if($.isFunction(callback)){callback.call(self,self.dropdown);}
return self;},_setText:function(elem,currentText){var self=this;if(self.options["html"]){elem.html(currentText);}
else{elem.text(currentText);}
return self;},open:function(callback){var self=this,showEffect=self.options["showEffect"],showEffectSpeed=self.options["showEffectSpeed"],showEffectOptions=self.options["showEffectOptions"],isNative=self.options["native"],isMobile=self.isMobile;if(!self.listItems.length||self.dropdown.hasClass(self.theme["disabled"])){return self;}
if((!isNative&&!isMobile)&&!this.list.is(":visible")){self.triggerEvent("open");if(self._dynamicPositioning&&self.options["dynamicPositioning"]){self._dynamicPositioning();}
if(showEffect==="none"){self.list.show();}
else if(showEffect==="show"||showEffect==="slideDown"||showEffect==="fadeIn"){self.list[showEffect](showEffectSpeed);}
else{self.list.show(showEffect,showEffectOptions,showEffectSpeed);}
self.list.promise().done(function(){self._scrollToView("search");});}
self._callbackSupport(callback);return self;},close:function(callback){var self=this,hideEffect=self.options["hideEffect"],hideEffectSpeed=self.options["hideEffectSpeed"],hideEffectOptions=self.options["hideEffectOptions"],isNative=self.options["native"],isMobile=self.isMobile;if((!isNative&&!isMobile)&&self.list.is(":visible")){self.triggerEvent("close");if(hideEffect==="none"){self.list.hide();}
else if(hideEffect==="hide"||hideEffect==="slideUp"||hideEffect==="fadeOut"){self.list[hideEffect](hideEffectSpeed);}
else{self.list.hide(hideEffect,hideEffectOptions,hideEffectSpeed);}}
self._callbackSupport(callback);return self;},toggle:function(){var self=this,listIsVisible=self.list.is(":visible");if(listIsVisible){self.close();}
else if(!listIsVisible){self.open();}},_keyMappings:{"38":"up","40":"down","13":"enter","8":"backspace","9":"tab","32":"space","27":"esc"},_keydownMethods:function(){var self=this,moveToOption=self.list.is(":visible")||!self.options["keydownOpen"];return{"down":function(){if(self.moveDown&&moveToOption){self.moveDown();}},"up":function(){if(self.moveUp&&moveToOption){self.moveUp();}},"enter":function(){var activeElem=self.listItems.eq(self.currentFocus);self._update(activeElem);if(activeElem.attr("data-preventclose")!=="true"){self.close();}
self.triggerEvent("enter");},"tab":function(){self.triggerEvent("tab-blur");self.close();},"backspace":function(){self.triggerEvent("backspace");},"esc":function(){self.close();}};},_eventHandlers:function(){var self=this,nativeMousedown=self.options["nativeMousedown"],customShowHideEvent=self.options["customShowHideEvent"],currentDataText,currentText,focusClass=self.focusClass,hoverClass=self.hoverClass,openClass=self.openClass;this.dropdown.on({"click.selectBoxIt":function(){self.dropdown.trigger("focus",true);if(!self.originalElem.disabled){self.triggerEvent("click");if(!nativeMousedown&&!customShowHideEvent){self.toggle();}}},"mousedown.selectBoxIt":function(){$(this).data("mdown",true);self.triggerEvent("mousedown");if(nativeMousedown&&!customShowHideEvent){self.toggle();}},"mouseup.selectBoxIt":function(){self.triggerEvent("mouseup");},"blur.selectBoxIt":function(){if(self.blur){self.triggerEvent("blur");self.close();$(this).removeClass(focusClass);}},"focus.selectBoxIt":function(event,internal){var mdown=$(this).data("mdown");$(this).removeData("mdown");if(!mdown&&!internal){setTimeout(function(){self.triggerEvent("tab-focus");},0);}
if(!internal){if(!$(this).hasClass(self.theme["disabled"])){$(this).addClass(focusClass);}
self.triggerEvent("focus");}},"keydown.selectBoxIt":function(e){var currentKey=self._keyMappings[e.keyCode],keydownMethod=self._keydownMethods()[currentKey];if(keydownMethod){keydownMethod();if(self.options["keydownOpen"]&&(currentKey==="up"||currentKey==="down")){self.open();}}
if(keydownMethod&&currentKey!=="tab"){e.preventDefault();}},"keypress.selectBoxIt":function(e){var currentKey=e.charCode||e.keyCode,key=self._keyMappings[e.charCode||e.keyCode],alphaNumericKey=String.fromCharCode(currentKey);if(self.search&&(!key||(key&&key==="space"))){self.search(alphaNumericKey,true,true);}
if(key==="space"){e.preventDefault();}},"mouseenter.selectBoxIt":function(){self.triggerEvent("mouseenter");},"mouseleave.selectBoxIt":function(){self.triggerEvent("mouseleave");}});self.list.on({"mouseover.selectBoxIt":function(){self.blur=false;},"mouseout.selectBoxIt":function(){self.blur=true;},"focusin.selectBoxIt":function(){self.dropdown.trigger("focus",true);}});self.list.on({"mousedown.selectBoxIt":function(){self._update($(this));self.triggerEvent("option-click");if($(this).attr("data-disabled")==="false"&&$(this).attr("data-preventclose")!=="true"){self.close();}
setTimeout(function(){self.dropdown.trigger('focus',true);},0);},"focusin.selectBoxIt":function(){self.listItems.not($(this)).removeAttr("data-active");$(this).attr("data-active","");var listIsHidden=self.list.is(":hidden");if((self.options["searchWhenHidden"]&&listIsHidden)||self.options["aggressiveChange"]||(listIsHidden&&self.options["selectWhenHidden"])){self._update($(this));}
$(this).addClass(focusClass);},"mouseup.selectBoxIt":function(){if(nativeMousedown&&!customShowHideEvent){self._update($(this));self.triggerEvent("option-mouseup");if($(this).attr("data-disabled")==="false"&&$(this).attr("data-preventclose")!=="true"){self.close();}}},"mouseenter.selectBoxIt":function(){if($(this).attr("data-disabled")==="false"){self.listItems.removeAttr("data-active");$(this).addClass(focusClass).attr("data-active","");self.listItems.not($(this)).removeClass(focusClass);$(this).addClass(focusClass);self.currentFocus=+$(this).attr("id");}},"mouseleave.selectBoxIt":function(){if($(this).attr("data-disabled")==="false"){self.listItems.not($(this)).removeClass(focusClass).removeAttr("data-active");$(this).addClass(focusClass);self.currentFocus=+$(this).attr("id");}},"blur.selectBoxIt":function(){$(this).removeClass(focusClass);}},".selectboxit-option");self.list.on({"click.selectBoxIt":function(ev){ev.preventDefault();}},"a");self.selectBox.on({"change.selectBoxIt, internal-change.selectBoxIt":function(event,internal){var currentOption,currentDataSelectedText;if(!internal){currentOption=self.list.find('li[data-val="'+self.originalElem.value+'"]');if(currentOption.length){self.listItems.eq(self.currentFocus).removeClass(self.focusClass);self.currentFocus=+currentOption.attr("id");}}
currentOption=self.listItems.eq(self.currentFocus);currentDataSelectedText=currentOption.attr("data-selectedtext");currentDataText=currentOption.attr("data-text");currentText=currentDataText?currentDataText:currentOption.find("a").text();self._setText(self.dropdownText,currentDataSelectedText||currentText);self.dropdownText.attr("data-val",self.originalElem.value);if(currentOption.find("i").attr("class")){self.dropdownImage.attr("class",currentOption.find("i").attr("class")).addClass("selectboxit-default-icon");self.dropdownImage.attr("style",currentOption.find("i").attr("style"));}
self.triggerEvent("changed");},"disable.selectBoxIt":function(){self.dropdown.addClass(self.theme["disabled"]);},"enable.selectBoxIt":function(){self.dropdown.removeClass(self.theme["disabled"]);},"open.selectBoxIt":function(){var currentElem=self.list.find("li[data-val='"+self.dropdownText.attr("data-val")+"']"),activeElem;if(!currentElem.length){currentElem=self.listItems.not("[data-disabled=true]").first();}
self.currentFocus=+currentElem.attr("id");activeElem=self.listItems.eq(self.currentFocus);self.dropdown.addClass(openClass).removeClass(hoverClass).addClass(focusClass);self.listItems.removeClass(self.selectedClass).removeAttr("data-active").not(activeElem).removeClass(focusClass);activeElem.addClass(self.selectedClass).addClass(focusClass);if(self.options.hideCurrent){self.listItems.show();activeElem.hide();}},"close.selectBoxIt":function(){self.dropdown.removeClass(openClass);},"blur.selectBoxIt":function(){self.dropdown.removeClass(focusClass);},"mouseenter.selectBoxIt":function(){if(!$(this).hasClass(self.theme["disabled"])){self.dropdown.addClass(hoverClass);}},"mouseleave.selectBoxIt":function(){self.dropdown.removeClass(hoverClass);},"destroy":function(ev){ev.preventDefault();ev.stopPropagation();}});return self;},_update:function(elem){var self=this,currentDataSelectedText,currentDataText,currentText,defaultText=self.options["defaultText"]||self.selectBox.attr("data-text"),currentElem=self.listItems.eq(self.currentFocus);if(elem.attr("data-disabled")==="false"){currentDataSelectedText=self.listItems.eq(self.currentFocus).attr("data-selectedtext");currentDataText=currentElem.attr("data-text");currentText=currentDataText?currentDataText:currentElem.text();if((defaultText&&self.options["html"]?self.dropdownText.html()===defaultText:self.dropdownText.text()===defaultText)&&self.selectBox.val()===elem.attr("data-val")){self.triggerEvent("change");}
else{self.selectBox.val(elem.attr("data-val"));self.currentFocus=+elem.attr("id");if(self.originalElem.value!==self.dropdownText.attr("data-val")){self.triggerEvent("change");}}}},_addClasses:function(obj){var self=this,focusClass=self.focusClass=obj.focus,hoverClass=self.hoverClass=obj.hover,buttonClass=obj.button,listClass=obj.list,arrowClass=obj.arrow,containerClass=obj.container,openClass=self.openClass=obj.open;self.selectedClass="selectboxit-selected";self.downArrow.addClass(self.selectBox.attr("data-downarrow")||self.options["downArrowIcon"]||arrowClass);self.dropdownContainer.addClass(containerClass);self.dropdown.addClass(buttonClass);self.list.addClass(listClass);return self;},refresh:function(callback,internal){var self=this;self._destroySelectBoxIt()._create(true);if(!internal){self.triggerEvent("refresh");}
self._callbackSupport(callback);return self;},htmlEscape:function(str){return String(str).replace(/&/g,"&amp;").replace(/"/g,"&quot;").replace(/'/g,"&#39;").replace(/</g,"&lt;").replace(/>/g,"&gt;");},triggerEvent:function(eventName){var self=this,currentIndex=self.options["showFirstOption"]?self.currentFocus:((self.currentFocus-1)>=0?self.currentFocus:0);self.selectBox.trigger(eventName,{"selectbox":self.selectBox,"selectboxOption":self.selectItems.eq(currentIndex),"dropdown":self.dropdown,"dropdownOption":self.listItems.eq(self.currentFocus)});return self;},_copyAttributes:function(){var self=this;if(self._addSelectBoxAttributes){self._addSelectBoxAttributes();}
return self;},_realOuterWidth:function(elem){if(elem.is(":visible")){return elem.outerWidth(true);}
var self=this,clonedElem=elem.clone(),outerWidth;clonedElem.css({"visibility":"hidden","display":"block","position":"absolute"}).appendTo("body");outerWidth=clonedElem.outerWidth(true);clonedElem.remove();return outerWidth;}});var selectBoxIt=$.selectBox.selectBoxIt.prototype;selectBoxIt.add=function(data,callback){this._populate(data,function(data){var self=this,dataType=$.type(data),value,x=0,dataLength,elems=[],isJSON=self._isJSON(data),parsedJSON=isJSON&&self._parseJSON(data);if(data&&(dataType==="array"||(isJSON&&parsedJSON.data&&$.type(parsedJSON.data)==="array"))||(dataType==="object"&&data.data&&$.type(data.data)==="array")){if(self._isJSON(data)){data=parsedJSON;}
if(data.data){data=data.data;}
for(dataLength=data.length;x<=dataLength-1;x+=1){value=data[x];if($.isPlainObject(value)){elems.push($("<option/>",value));}
else if($.type(value)==="string"){elems.push($("<option/>",{text:value,value:value}));}}
self.selectBox.append(elems);}
else if(data&&dataType==="string"&&!self._isJSON(data)){self.selectBox.append(data);}
else if(data&&dataType==="object"){self.selectBox.append($("<option/>",data));}
else if(data&&self._isJSON(data)&&$.isPlainObject(self._parseJSON(data))){self.selectBox.append($("<option/>",self._parseJSON(data)));}
if(self.dropdown){self.refresh(function(){self._callbackSupport(callback);},true);}else{self._callbackSupport(callback);}
return self;});};selectBoxIt._parseJSON=function(data){return(JSON&&JSON.parse&&JSON.parse(data))||$.parseJSON(data);};selectBoxIt._isJSON=function(data){var self=this,json;try{json=self._parseJSON(data);return true;}catch(e){return false;}};selectBoxIt._populate=function(data,callback){var self=this;data=$.isFunction(data)?data.call():data;if(self.isDeferred(data)){data.done(function(returnedData){callback.call(self,returnedData);});}
else{callback.call(self,data);}
return self;};selectBoxIt._ariaAccessibility=function(){var self=this,dropdownLabel=$("label[for='"+self.originalElem.id+"']");self.dropdownContainer.attr({"role":"combobox","aria-autocomplete":"list","aria-haspopup":"true","aria-expanded":"false","aria-owns":self.list[0].id});self.dropdownText.attr({"aria-live":"polite"});self.dropdown.on({"disable.selectBoxIt":function(){self.dropdownContainer.attr("aria-disabled","true");},"enable.selectBoxIt":function(){self.dropdownContainer.attr("aria-disabled","false");}});if(dropdownLabel.length){self.dropdownContainer.attr("aria-labelledby",dropdownLabel[0].id);}
self.list.attr({"role":"listbox","aria-hidden":"true"});self.listItems.attr({"role":"option"});self.selectBox.on({"open.selectBoxIt":function(){self.list.attr("aria-hidden","false");self.dropdownContainer.attr("aria-expanded","true");},"close.selectBoxIt":function(){self.list.attr("aria-hidden","true");self.dropdownContainer.attr("aria-expanded","false");}});return self;};selectBoxIt._addSelectBoxAttributes=function(){var self=this;self._addAttributes(self.selectBox.prop("attributes"),self.dropdown);self.selectItems.each(function(iterator){self._addAttributes($(this).prop("attributes"),self.listItems.eq(iterator));});return self;};selectBoxIt._addAttributes=function(arr,elem){var self=this,whitelist=self.options["copyAttributes"];if(arr.length){$.each(arr,function(iterator,property){var propName=(property.name).toLowerCase(),propValue=property.value;if(propValue!=="null"&&($.inArray(propName,whitelist)!==-1||propName.indexOf("data")!==-1)){elem.attr(propName,propValue);}});}
return self;};selectBoxIt.destroy=function(callback){var self=this;self._destroySelectBoxIt();self.widgetProto.destroy.call(self);self._callbackSupport(callback);return self;};selectBoxIt._destroySelectBoxIt=function(){var self=this;self.dropdown.off(".selectBoxIt");if($.contains(self.dropdownContainer[0],self.originalElem)){self.dropdownContainer.before(self.selectBox);}
self.dropdownContainer.remove();self.selectBox.removeAttr("style").attr("style",self.selectBoxStyles);self.selectBox.show();self.triggerEvent("destroy");return self;};selectBoxIt.disable=function(callback){var self=this;if(!self.options["disabled"]){self.close();self.selectBox.attr("disabled","disabled");self.dropdown.removeAttr("tabindex").removeClass(self.theme["enabled"]).addClass(self.theme["disabled"]);self.setOption("disabled",true);self.triggerEvent("disable");}
self._callbackSupport(callback);return self;};selectBoxIt.disableOption=function(index,callback){var self=this,currentSelectBoxOption,hasNextEnabled,hasPreviousEnabled,type=$.type(index);if(type==="number"){self.close();currentSelectBoxOption=self.selectBox.find("option").eq(index);self.triggerEvent("disable-option");currentSelectBoxOption.attr("disabled","disabled");self.listItems.eq(index).attr("data-disabled","true").addClass(self.theme["disabled"]);if(self.currentFocus===index){hasNextEnabled=self.listItems.eq(self.currentFocus).nextAll("li").not("[data-disabled='true']").first().length;hasPreviousEnabled=self.listItems.eq(self.currentFocus).prevAll("li").not("[data-disabled='true']").first().length;if(hasNextEnabled){self.moveDown();}
else if(hasPreviousEnabled){self.moveUp();}
else{self.disable();}}}
self._callbackSupport(callback);return self;};selectBoxIt._isDisabled=function(callback){var self=this;if(self.originalElem.disabled){self.disable();}
return self;};selectBoxIt._dynamicPositioning=function(){var self=this;if($.type(self.listSize)==="number"){self.list.css("max-height",self.maxHeight||"none");}
else{var listOffsetTop=self.dropdown.offset().top,listHeight=self.list.data("max-height")||self.list.outerHeight(),selectBoxHeight=self.dropdown.outerHeight(),viewport=self.options["viewport"],viewportHeight=viewport.height(),viewportScrollTop=$.isWindow(viewport.get(0))?viewport.scrollTop():viewport.offset().top,topToBottom=(listOffsetTop+selectBoxHeight+listHeight<=viewportHeight+viewportScrollTop),bottomReached=!topToBottom;if(!self.list.data("max-height")){self.list.data("max-height",self.list.outerHeight());}
if(!bottomReached){self.list.css("max-height",listHeight);self.list.css("top","auto");}
else if((self.dropdown.offset().top-viewportScrollTop)>=listHeight){self.list.css("max-height",listHeight);self.list.css("top",(self.dropdown.position().top-self.list.outerHeight()));}
else{var outsideBottomViewport=Math.abs((listOffsetTop+selectBoxHeight+listHeight)-(viewportHeight+viewportScrollTop)),outsideTopViewport=Math.abs((self.dropdown.offset().top-viewportScrollTop)-listHeight);if(outsideBottomViewport<outsideTopViewport){self.list.css("max-height",listHeight-outsideBottomViewport-(selectBoxHeight/2));self.list.css("top","auto");}
else{self.list.css("max-height",listHeight-outsideTopViewport-(selectBoxHeight/2));self.list.css("top",(self.dropdown.position().top-self.list.outerHeight()));}}}
return self;};selectBoxIt.enable=function(callback){var self=this;if(self.options["disabled"]){self.triggerEvent("enable");self.selectBox.removeAttr("disabled");self.dropdown.attr("tabindex",0).removeClass(self.theme["disabled"]).addClass(self.theme["enabled"]);self.setOption("disabled",false);self._callbackSupport(callback);}
return self;};selectBoxIt.enableOption=function(index,callback){var self=this,currentSelectBoxOption,currentIndex=0,hasNextEnabled,hasPreviousEnabled,type=$.type(index);if(type==="number"){currentSelectBoxOption=self.selectBox.find("option").eq(index);self.triggerEvent("enable-option");currentSelectBoxOption.removeAttr("disabled");self.listItems.eq(index).attr("data-disabled","false").removeClass(self.theme["disabled"]);}
self._callbackSupport(callback);return self;};selectBoxIt.moveDown=function(callback){var self=this;self.currentFocus+=1;var disabled=self.listItems.eq(self.currentFocus).attr("data-disabled")==="true"?true:false,hasNextEnabled=self.listItems.eq(self.currentFocus).nextAll("li").not("[data-disabled='true']").first().length;if(self.currentFocus===self.listItems.length){self.currentFocus-=1;}
else if(disabled&&hasNextEnabled){self.listItems.eq(self.currentFocus-1).blur();self.moveDown();return;}
else if(disabled&&!hasNextEnabled){self.currentFocus-=1;}
else{self.listItems.eq(self.currentFocus-1).blur().end().eq(self.currentFocus).focusin();self._scrollToView("down");self.triggerEvent("moveDown");}
self._callbackSupport(callback);return self;};selectBoxIt.moveUp=function(callback){var self=this;self.currentFocus-=1;var disabled=self.listItems.eq(self.currentFocus).attr("data-disabled")==="true"?true:false,hasPreviousEnabled=self.listItems.eq(self.currentFocus).prevAll("li").not("[data-disabled='true']").first().length;if(self.currentFocus===-1){self.currentFocus+=1;}
else if(disabled&&hasPreviousEnabled){self.listItems.eq(self.currentFocus+1).blur();self.moveUp();return;}
else if(disabled&&!hasPreviousEnabled){self.currentFocus+=1;}
else{self.listItems.eq(this.currentFocus+1).blur().end().eq(self.currentFocus).focusin();self._scrollToView("up");self.triggerEvent("moveUp");}
self._callbackSupport(callback);return self;};selectBoxIt._setCurrentSearchOption=function(currentOption){var self=this;if((self.options["aggressiveChange"]||self.options["selectWhenHidden"]||self.listItems.eq(currentOption).is(":visible"))&&self.listItems.eq(currentOption).data("disabled")!==true){self.listItems.eq(self.currentFocus).blur();self.currentIndex=currentOption;self.currentFocus=currentOption;self.listItems.eq(self.currentFocus).focusin();self._scrollToView("search");self.triggerEvent("search");}
return self;};selectBoxIt._searchAlgorithm=function(currentIndex,alphaNumeric){var self=this,matchExists=false,x,y,arrayLength,currentSearch,textArray=self.textArray,currentText=self.currentText;for(x=currentIndex,arrayLength=textArray.length;x<arrayLength;x+=1){currentSearch=textArray[x];for(y=0;y<arrayLength;y+=1){if(textArray[y].search(alphaNumeric)!==-1){matchExists=true;y=arrayLength;}}
if(!matchExists){self.currentText=self.currentText.charAt(self.currentText.length-1).replace(/[|()\[{.+*?$\\]/g,"\\$0");currentText=self.currentText;}
alphaNumeric=new RegExp(currentText,"gi");if(currentText.length<3){alphaNumeric=new RegExp(currentText.charAt(0),"gi");if((currentSearch.charAt(0).search(alphaNumeric)!==-1)){self._setCurrentSearchOption(x);if((currentSearch.substring(0,currentText.length).toLowerCase()!==currentText.toLowerCase())||self.options["similarSearch"]){self.currentIndex+=1;}
return false;}}
else{if((currentSearch.search(alphaNumeric)!==-1)){self._setCurrentSearchOption(x);return false;}}
if(currentSearch.toLowerCase()===self.currentText.toLowerCase()){self._setCurrentSearchOption(x);self.currentText="";return false;}}
return true;};selectBoxIt.search=function(alphaNumericKey,callback,rememberPreviousSearch){var self=this;if(rememberPreviousSearch){self.currentText+=alphaNumericKey.replace(/[|()\[{.+*?$\\]/g,"\\$0");}
else{self.currentText=alphaNumericKey.replace(/[|()\[{.+*?$\\]/g,"\\$0");}
var searchResults=self._searchAlgorithm(self.currentIndex,new RegExp(self.currentText,"gi"));if(searchResults){self._searchAlgorithm(0,self.currentText);}
self._callbackSupport(callback);return self;};selectBoxIt._applyNativeSelect=function(){var self=this,currentOption,currentDataText,currentText;self.dropdownContainer.append(self.selectBox);self.dropdown.attr('tabindex','-1');self.selectBox.css({"display":"block","visibility":"visible","width":self.dropdown.outerWidth(),"height":self.dropdown.outerHeight(),"opacity":"0","position":"absolute","top":"0","left":"0","cursor":"pointer","z-index":"999999","margin":self.dropdown.css("margin"),"padding":"0","-webkit-appearance":"menulist-button"}).on({"changed.selectBoxIt":function(){currentOption=self.selectBox.find("option").filter(":selected");currentDataText=currentOption.attr("data-text");currentText=currentDataText?currentDataText:currentOption.text();self._setText(self.dropdownText,currentText);if(self.list.find('li[data-val="'+currentOption.val()+'"]').find("i").attr("class")){self.dropdownImage.attr("class",self.list.find('li[data-val="'+currentOption.val()+'"]').find("i").attr("class")).addClass("selectboxit-default-icon");}
self.triggerEvent("option-click");}});};selectBoxIt._mobile=function(callback){var self=this;if(self.isMobile){self._applyNativeSelect();}
return this;};selectBoxIt.remove=function(indexes,callback){var self=this,dataType=$.type(indexes),value,x=0,dataLength,elems="";if(dataType==="array"){for(dataLength=indexes.length;x<=dataLength-1;x+=1){value=indexes[x];if($.type(value)==="number"){if(elems.length){elems+=", option:eq("+value+")";}
else{elems+="option:eq("+value+")";}}}
self.selectBox.find(elems).remove();}
else if(dataType==="number"){self.selectBox.find("option").eq(indexes).remove();}
else{self.selectBox.find("option").remove();}
if(self.dropdown){self.refresh(function(){self._callbackSupport(callback);},true);}else{self._callbackSupport(callback);}
return self;};selectBoxIt.selectOption=function(val,callback){var self=this,type=$.type(val);if(type==="number"){self.selectBox.val(self.selectItems.eq(val).val()).change();}
else if(type==="string"){self.selectBox.val(val).change();}
self._callbackSupport(callback);return self;};selectBoxIt.setOption=function(key,value,callback){var self=this;if($.type(key)==="string"){self.options[key]=value;}
self.refresh(function(){self._callbackSupport(callback);},true);return self;};selectBoxIt.setOptions=function(newOptions,callback){var self=this;if($.isPlainObject(newOptions)){self.options=$.extend({},self.options,newOptions);}
self.refresh(function(){self._callbackSupport(callback);},true);return self;};selectBoxIt.wait=function(time,callback){var self=this;self.widgetProto._delay.call(self,callback,time);return self;};}));var Bubble={positionRight:"R",positionLeft:"L",positionCenter:"C",positionUnknown:"U",isBubbleVisible:{},elementIds:[],setDataBack:false};Bubble.showBubble=function(event){event.data.target=event.target;Bubble.show(event.data);if(jQuery.isFunction(event.preventDefault)){event.preventDefault();}};Bubble.show=function(data){var $position=data.position;var setDataBack=data.setDataBack;var $element=jQuery(data.target),elementId=$element.attr("id"),$bubble=jQuery("#bubble-"+elementId),$bubbleContent=jQuery("#bubbleContent-"+elementId),$bubbleArrow=jQuery("#bubbleArrow-"+elementId),$dataElement=jQuery("#"+elementId+"-data");if(Bubble.isBubbleVisible[elementId]){Bubble.isBubbleVisible[elementId]=!Bubble.isBubbleVisible[elementId];if($dataElement.size()>0){var contentData=$bubbleContent.html();$dataElement.html(contentData);$bubbleContent.html('');var arrayIndex=jQuery.inArray(elementId,Bubble.elementIds);if(arrayIndex>-1){Bubble.elementIds.splice(arrayIndex,1);}}}else{Bubble.isBubbleVisible[elementId]=true;if($bubble.length===0){$bubble=jQuery("<span>").attr("id","bubble-"+elementId).addClass("bubble");$element.parent().append($bubble);$bubbleContent=jQuery("<span>").attr("id","bubbleContent-"+elementId).addClass("bubble-content");$bubbleArrow=jQuery("<span>").attr("id","bubbleArrow-"+elementId).addClass("bubble-arrow");$bubble.append($bubbleContent).append($bubbleArrow);}
$bubbleArrow.removeClass("bubble-arrow-right");$bubbleArrow.removeClass("bubble-arrow-left");if($dataElement.size()>0){var contentData=$dataElement.html();$bubbleContent.html(contentData);$dataElement.html('');}
else{$bubbleContent.html("No data available to display");}
if(jQuery.inArray(elementId,Bubble.elementIds)==-1){Bubble.elementIds.push(elementId);}
if($position===Bubble.positionLeft){Bubble.setLeft({$element:$element,$bubbleArrow:$bubbleArrow,$bubble:$bubble,$bubbleContent:$bubbleContent});}
else if($position===Bubble.positionRight){Bubble.setRight({$element:$element,$bubbleArrow:$bubbleArrow,$bubble:$bubble,$bubbleContent:$bubbleContent});}
else if($position===Bubble.positionCenter){Bubble.setCenter({$element:$element,$bubbleArrow:$bubbleArrow,$bubble:$bubble,$bubbleContent:$bubbleContent});}
else{Bubble.setWithElementLocation({$element:$element,$bubbleArrow:$bubbleArrow,$bubble:$bubble,$bubbleContent:$bubbleContent});}}
$bubble.toggle();};Bubble.hide=function(e){var elementId=e.data.elementId;if(Bubble.isBubbleVisible[elementId]){Bubble.isBubbleVisible[elementId]=!Bubble.isBubbleVisible[elementId];var $bubble=jQuery("#bubble-"+elementId),$bubbleContent=jQuery("#bubbleContent-"+elementId),data=$bubbleContent.html(),$dataElement=jQuery("#"+elementId+"-data");$dataElement.html(data);$bubbleContent.html('');var arrayIndex=jQuery.inArray(elementId,Bubble.elementIds);if(arrayIndex>-1){Bubble.elementIds.splice(arrayIndex,1);}
$bubble.toggle();}};Bubble.forceHideAll=function(e){var bubbleCnt=Bubble.elementIds.length;for(var i=0;i<bubbleCnt;i++){var elementId=Bubble.elementIds[i];e["data"]={'elementId':elementId};Bubble.hide(e);}};Bubble.hideAll=function(e){var bubbleCnt=Bubble.elementIds.length;for(var i=0;i<bubbleCnt;i++){var elementId=Bubble.elementIds[i];if(!jQuery(e.target).closest('#'+elementId)[0]&&!jQuery(e.target).closest('#bubble-'+elementId)[0]){e["data"]={'elementId':elementId};Bubble.hide(e);}}};Bubble.setRight=function(data){var element=data.$element.get(0);var top=jQuery(element).position().top+data.$element.outerHeight();var bubbleWidth=data.$bubble.outerWidth();var right=jQuery(element).position().left-(bubbleWidth-(data.$element.outerWidth()));data.$bubbleArrow.addClass("bubble-arrow-right");data.$bubbleArrow.css({left:(bubbleWidth-32)+"px"});data.$bubble.css({top:top+"px",left:right+"px"});};Bubble.setCenter=function(data){var element=data.$element.get(0);var top=jQuery(element).position().top+data.$element.outerHeight();var center=parseInt(data.$element.outerWidth()/2);var bubbleWidth=data.$bubble.outerWidth();var left=jQuery(element).position().left+center;var bubbleCenter=left-(bubbleWidth/2);data.$bubbleArrow.css({left:(bubbleWidth/2)+"px"});data.$bubbleArrow.addClass("bubble-arrow-center")
data.$bubble.css({top:top+"px",left:bubbleCenter+"px"});};Bubble.setLeft=function(data){var element=data.$element.get(0);var top=jQuery(element).position().top+data.$element.outerHeight();var bubbleWidth=data.$bubble.outerWidth();var right=jQuery(element).position().left-12;data.$bubbleArrow.css({width:bubbleWidth+"px",left:5+"px"});data.$bubble.css({top:top+"px",left:right+"px"});};Bubble.setWithElementLocation=function(data){var $element=data.$element.get(0);var top=$element.position().top;var left=$element.position().left;var height=$element.outerHeight();var width=$element.outerWidth();var bubbleWidth=$bubble.outerWidth();var bubbleLeft=(left+(width/2))-bubbleWidth/2;var arrowLeft=(bubbleWidth/2.5);$bubble.css({top:(top+height)+"px",left:bubbleLeft+"px"});$bubbleArrow.css("left",arrowLeft+"px");if(bubbleWidth>width){var windowWidth=jQuery(window).width();var right=windowWidth-(left+width);if(right<bubbleWidth){bubbleLeft=windowWidth-(bubbleWidth+right);$bubble.css({left:bubbleLeft+"px"});$bubbleArrow.css({left:(bubbleWidth)+"px"});$bubbleArrow.addClass("bubble-arrow-right");}
else if(bubbleLeft<bubbleWidth){bubbleLeft=left;var arrowLeft=left-4;$bubbleArrow.css({left:arrowLeft+"px"});$bubbleArrow.addClass("bubble-arrow-left");$bubble.css({left:bubbleLeft+"px"});}}};MendeleyImporterApi={};(function(api){var data={},bookmarkletUrl=MendeleybookmarkletUrl;init();function init(){api.open=open;api.close=close;api.setOpenedWithApi=getSetter('openedWithApi');api.getOpenedWithApi=getGetter('openedWithApi');var methods=['HostId','UserIdentityCallback','DataCallback'];for(var i=0,l=methods.length;i<l;i++){var key=methods[i];api['register'+key]=getSetter(key);api['get'+key]=getGetter(key);}}
function getGetter(key){return function(){return data[key];};}
function getSetter(key){return function(value){data[key]=value;};}
function open(){this.setOpenedWithApi(true);document.getElementsByTagName('body')[0].appendChild(document.createElement('script')).setAttribute('src',bookmarkletUrl);}
function close(){try{document.getElementById('mendeley-bookmarklet-close').click();}catch(e){}}})(MendeleyImporterApi);